//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QueryDemoConsole
{
  using WiLinq.LinqProvider;
  
  [WiLinq.LinqProvider.Extensions.WorkItemTypeAttribute("Task")]
  public partial class Task : WiLinq.LinqProvider.Extensions.WorkItemBase {
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.Common.Activity")]
    public virtual string Activity {
      get {
        return this.WorkItem.Field<string>("Microsoft.VSTS.Common.Activity");
      }
      set {
        this.WorkItem.SetField<string>("Microsoft.VSTS.Common.Activity", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("System.AuthorizedAs")]
    public virtual string AuthorizedAs {
      get {
        return this.WorkItem.Field<string>("System.AuthorizedAs");
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("System.AuthorizedDate")]
    public virtual System.Nullable<System.DateTime> AuthorizedDate {
      get {
        return this.WorkItem.Field<System.Nullable<System.DateTime>>("System.AuthorizedDate");
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.Common.BacklogPriority")]
    public virtual System.Nullable<double> BacklogPriority {
      get {
        return this.WorkItem.Field<System.Nullable<double>>("Microsoft.VSTS.Common.BacklogPriority");
      }
      set {
        this.WorkItem.SetField<System.Nullable<double>>("Microsoft.VSTS.Common.BacklogPriority", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.CMMI.Blocked")]
    public virtual string Blocked {
      get {
        return this.WorkItem.Field<string>("Microsoft.VSTS.CMMI.Blocked");
      }
      set {
        this.WorkItem.SetField<string>("Microsoft.VSTS.CMMI.Blocked", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.Common.ClosedDate")]
    public virtual System.Nullable<System.DateTime> ClosedDate {
      get {
        return this.WorkItem.Field<System.Nullable<System.DateTime>>("Microsoft.VSTS.Common.ClosedDate");
      }
      set {
        this.WorkItem.SetField<System.Nullable<System.DateTime>>("Microsoft.VSTS.Common.ClosedDate", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.Build.IntegrationBuild")]
    public virtual string IntegrationBuild {
      get {
        return this.WorkItem.Field<string>("Microsoft.VSTS.Build.IntegrationBuild");
      }
      set {
        this.WorkItem.SetField<string>("Microsoft.VSTS.Build.IntegrationBuild", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.Scheduling.RemainingWork")]
    public virtual System.Nullable<double> RemainingWork {
      get {
        return this.WorkItem.Field<System.Nullable<double>>("Microsoft.VSTS.Scheduling.RemainingWork");
      }
      set {
        this.WorkItem.SetField<System.Nullable<double>>("Microsoft.VSTS.Scheduling.RemainingWork", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("System.RevisedDate")]
    public virtual System.Nullable<System.DateTime> RevisedDate {
      get {
        return this.WorkItem.Field<System.Nullable<System.DateTime>>("System.RevisedDate");
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("System.Tags")]
    public virtual string Tags {
      get {
        return this.WorkItem.Field<string>("System.Tags");
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("System.Watermark")]
    public virtual System.Nullable<int> Watermark {
      get {
        return this.WorkItem.Field<System.Nullable<int>>("System.Watermark");
      }
    }
  }
  
  [WiLinq.LinqProvider.Extensions.WorkItemTypeAttribute("Bug")]
  public partial class Bug : WiLinq.LinqProvider.Extensions.WorkItemBase {
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.Common.AcceptanceCriteria")]
    public virtual string AcceptanceCriteria {
      get {
        return this.WorkItem.Field<string>("Microsoft.VSTS.Common.AcceptanceCriteria");
      }
      set {
        this.WorkItem.SetField<string>("Microsoft.VSTS.Common.AcceptanceCriteria", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("System.AuthorizedAs")]
    public virtual string AuthorizedAs {
      get {
        return this.WorkItem.Field<string>("System.AuthorizedAs");
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("System.AuthorizedDate")]
    public virtual System.Nullable<System.DateTime> AuthorizedDate {
      get {
        return this.WorkItem.Field<System.Nullable<System.DateTime>>("System.AuthorizedDate");
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.Common.BacklogPriority")]
    public virtual System.Nullable<double> BacklogPriority {
      get {
        return this.WorkItem.Field<System.Nullable<double>>("Microsoft.VSTS.Common.BacklogPriority");
      }
      set {
        this.WorkItem.SetField<System.Nullable<double>>("Microsoft.VSTS.Common.BacklogPriority", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.Common.ClosedDate")]
    public virtual System.Nullable<System.DateTime> ClosedDate {
      get {
        return this.WorkItem.Field<System.Nullable<System.DateTime>>("Microsoft.VSTS.Common.ClosedDate");
      }
      set {
        this.WorkItem.SetField<System.Nullable<System.DateTime>>("Microsoft.VSTS.Common.ClosedDate", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.Scheduling.Effort")]
    public virtual System.Nullable<double> Effort {
      get {
        return this.WorkItem.Field<System.Nullable<double>>("Microsoft.VSTS.Scheduling.Effort");
      }
      set {
        this.WorkItem.SetField<System.Nullable<double>>("Microsoft.VSTS.Scheduling.Effort", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.Build.FoundIn")]
    public virtual string FoundIn {
      get {
        return this.WorkItem.Field<string>("Microsoft.VSTS.Build.FoundIn");
      }
      set {
        this.WorkItem.SetField<string>("Microsoft.VSTS.Build.FoundIn", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.Build.IntegrationBuild")]
    public virtual string IntegrationBuild {
      get {
        return this.WorkItem.Field<string>("Microsoft.VSTS.Build.IntegrationBuild");
      }
      set {
        this.WorkItem.SetField<string>("Microsoft.VSTS.Build.IntegrationBuild", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.TCM.ReproSteps")]
    public virtual string ReproSteps {
      get {
        return this.WorkItem.Field<string>("Microsoft.VSTS.TCM.ReproSteps");
      }
      set {
        this.WorkItem.SetField<string>("Microsoft.VSTS.TCM.ReproSteps", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("System.RevisedDate")]
    public virtual System.Nullable<System.DateTime> RevisedDate {
      get {
        return this.WorkItem.Field<System.Nullable<System.DateTime>>("System.RevisedDate");
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.Common.Severity")]
    public virtual string Severity {
      get {
        return this.WorkItem.Field<string>("Microsoft.VSTS.Common.Severity");
      }
      set {
        this.WorkItem.SetField<string>("Microsoft.VSTS.Common.Severity", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.TCM.SystemInfo")]
    public virtual string SystemInfo {
      get {
        return this.WorkItem.Field<string>("Microsoft.VSTS.TCM.SystemInfo");
      }
      set {
        this.WorkItem.SetField<string>("Microsoft.VSTS.TCM.SystemInfo", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("System.Tags")]
    public virtual string Tags {
      get {
        return this.WorkItem.Field<string>("System.Tags");
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("System.Watermark")]
    public virtual System.Nullable<int> Watermark {
      get {
        return this.WorkItem.Field<System.Nullable<int>>("System.Watermark");
      }
    }
  }
  
  [WiLinq.LinqProvider.Extensions.WorkItemTypeAttribute("Code Review Request")]
  public partial class CodeReviewRequest : WiLinq.LinqProvider.Extensions.WorkItemBase {
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.CodeReview.Context")]
    public virtual string AssociatedContext {
      get {
        return this.WorkItem.Field<string>("Microsoft.VSTS.CodeReview.Context");
      }
      set {
        this.WorkItem.SetField<string>("Microsoft.VSTS.CodeReview.Context", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.CodeReview.ContextCode")]
    public virtual System.Nullable<int> AssociatedContextCode {
      get {
        return this.WorkItem.Field<System.Nullable<int>>("Microsoft.VSTS.CodeReview.ContextCode");
      }
      set {
        this.WorkItem.SetField<System.Nullable<int>>("Microsoft.VSTS.CodeReview.ContextCode", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.CodeReview.ContextOwner")]
    public virtual string AssociatedContextOwner {
      get {
        return this.WorkItem.Field<string>("Microsoft.VSTS.CodeReview.ContextOwner");
      }
      set {
        this.WorkItem.SetField<string>("Microsoft.VSTS.CodeReview.ContextOwner", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.CodeReview.ContextType")]
    public virtual string AssociatedContextType {
      get {
        return this.WorkItem.Field<string>("Microsoft.VSTS.CodeReview.ContextType");
      }
      set {
        this.WorkItem.SetField<string>("Microsoft.VSTS.CodeReview.ContextType", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("System.AuthorizedAs")]
    public virtual string AuthorizedAs {
      get {
        return this.WorkItem.Field<string>("System.AuthorizedAs");
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("System.AuthorizedDate")]
    public virtual System.Nullable<System.DateTime> AuthorizedDate {
      get {
        return this.WorkItem.Field<System.Nullable<System.DateTime>>("System.AuthorizedDate");
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.Common.ClosedBy")]
    public virtual string ClosedBy {
      get {
        return this.WorkItem.Field<string>("Microsoft.VSTS.Common.ClosedBy");
      }
      set {
        this.WorkItem.SetField<string>("Microsoft.VSTS.Common.ClosedBy", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.Common.ClosedDate")]
    public virtual System.Nullable<System.DateTime> ClosedDate {
      get {
        return this.WorkItem.Field<System.Nullable<System.DateTime>>("Microsoft.VSTS.Common.ClosedDate");
      }
      set {
        this.WorkItem.SetField<System.Nullable<System.DateTime>>("Microsoft.VSTS.Common.ClosedDate", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.CodeReview.ClosedStatus")]
    public virtual string ClosedStatus {
      get {
        return this.WorkItem.Field<string>("Microsoft.VSTS.CodeReview.ClosedStatus");
      }
      set {
        this.WorkItem.SetField<string>("Microsoft.VSTS.CodeReview.ClosedStatus", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.CodeReview.ClosedStatusCode")]
    public virtual System.Nullable<int> ClosedStatusCode {
      get {
        return this.WorkItem.Field<System.Nullable<int>>("Microsoft.VSTS.CodeReview.ClosedStatusCode");
      }
      set {
        this.WorkItem.SetField<System.Nullable<int>>("Microsoft.VSTS.CodeReview.ClosedStatusCode", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.CodeReview.ClosingComment")]
    public virtual string ClosingComment {
      get {
        return this.WorkItem.Field<string>("Microsoft.VSTS.CodeReview.ClosingComment");
      }
      set {
        this.WorkItem.SetField<string>("Microsoft.VSTS.CodeReview.ClosingComment", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.Build.IntegrationBuild")]
    public virtual string IntegrationBuild {
      get {
        return this.WorkItem.Field<string>("Microsoft.VSTS.Build.IntegrationBuild");
      }
      set {
        this.WorkItem.SetField<string>("Microsoft.VSTS.Build.IntegrationBuild", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("System.RevisedDate")]
    public virtual System.Nullable<System.DateTime> RevisedDate {
      get {
        return this.WorkItem.Field<System.Nullable<System.DateTime>>("System.RevisedDate");
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.Common.StateCode")]
    public virtual System.Nullable<int> StateCode {
      get {
        return this.WorkItem.Field<System.Nullable<int>>("Microsoft.VSTS.Common.StateCode");
      }
      set {
        this.WorkItem.SetField<System.Nullable<int>>("Microsoft.VSTS.Common.StateCode", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("System.Tags")]
    public virtual string Tags {
      get {
        return this.WorkItem.Field<string>("System.Tags");
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("System.Watermark")]
    public virtual System.Nullable<int> Watermark {
      get {
        return this.WorkItem.Field<System.Nullable<int>>("System.Watermark");
      }
    }
  }
  
  [WiLinq.LinqProvider.Extensions.WorkItemTypeAttribute("Code Review Response")]
  public partial class CodeReviewResponse : WiLinq.LinqProvider.Extensions.WorkItemBase {
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.CodeReview.AcceptedBy")]
    public virtual string AcceptedBy {
      get {
        return this.WorkItem.Field<string>("Microsoft.VSTS.CodeReview.AcceptedBy");
      }
      set {
        this.WorkItem.SetField<string>("Microsoft.VSTS.CodeReview.AcceptedBy", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.CodeReview.AcceptedDate")]
    public virtual System.Nullable<System.DateTime> AcceptedDate {
      get {
        return this.WorkItem.Field<System.Nullable<System.DateTime>>("Microsoft.VSTS.CodeReview.AcceptedDate");
      }
      set {
        this.WorkItem.SetField<System.Nullable<System.DateTime>>("Microsoft.VSTS.CodeReview.AcceptedDate", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("System.AuthorizedAs")]
    public virtual string AuthorizedAs {
      get {
        return this.WorkItem.Field<string>("System.AuthorizedAs");
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("System.AuthorizedDate")]
    public virtual System.Nullable<System.DateTime> AuthorizedDate {
      get {
        return this.WorkItem.Field<System.Nullable<System.DateTime>>("System.AuthorizedDate");
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.Common.ClosedBy")]
    public virtual string ClosedBy {
      get {
        return this.WorkItem.Field<string>("Microsoft.VSTS.Common.ClosedBy");
      }
      set {
        this.WorkItem.SetField<string>("Microsoft.VSTS.Common.ClosedBy", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.Common.ClosedDate")]
    public virtual System.Nullable<System.DateTime> ClosedDate {
      get {
        return this.WorkItem.Field<System.Nullable<System.DateTime>>("Microsoft.VSTS.Common.ClosedDate");
      }
      set {
        this.WorkItem.SetField<System.Nullable<System.DateTime>>("Microsoft.VSTS.Common.ClosedDate", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.CodeReview.ClosedStatus")]
    public virtual string ClosedStatus {
      get {
        return this.WorkItem.Field<string>("Microsoft.VSTS.CodeReview.ClosedStatus");
      }
      set {
        this.WorkItem.SetField<string>("Microsoft.VSTS.CodeReview.ClosedStatus", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.CodeReview.ClosedStatusCode")]
    public virtual System.Nullable<int> ClosedStatusCode {
      get {
        return this.WorkItem.Field<System.Nullable<int>>("Microsoft.VSTS.CodeReview.ClosedStatusCode");
      }
      set {
        this.WorkItem.SetField<System.Nullable<int>>("Microsoft.VSTS.CodeReview.ClosedStatusCode", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.CodeReview.ClosingComment")]
    public virtual string ClosingComment {
      get {
        return this.WorkItem.Field<string>("Microsoft.VSTS.CodeReview.ClosingComment");
      }
      set {
        this.WorkItem.SetField<string>("Microsoft.VSTS.CodeReview.ClosingComment", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.Build.IntegrationBuild")]
    public virtual string IntegrationBuild {
      get {
        return this.WorkItem.Field<string>("Microsoft.VSTS.Build.IntegrationBuild");
      }
      set {
        this.WorkItem.SetField<string>("Microsoft.VSTS.Build.IntegrationBuild", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.Common.ReviewedBy")]
    public virtual string ReviewedBy {
      get {
        return this.WorkItem.Field<string>("Microsoft.VSTS.Common.ReviewedBy");
      }
      set {
        this.WorkItem.SetField<string>("Microsoft.VSTS.Common.ReviewedBy", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("System.RevisedDate")]
    public virtual System.Nullable<System.DateTime> RevisedDate {
      get {
        return this.WorkItem.Field<System.Nullable<System.DateTime>>("System.RevisedDate");
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.Common.StateCode")]
    public virtual System.Nullable<int> StateCode {
      get {
        return this.WorkItem.Field<System.Nullable<int>>("Microsoft.VSTS.Common.StateCode");
      }
      set {
        this.WorkItem.SetField<System.Nullable<int>>("Microsoft.VSTS.Common.StateCode", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("System.Tags")]
    public virtual string Tags {
      get {
        return this.WorkItem.Field<string>("System.Tags");
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("System.Watermark")]
    public virtual System.Nullable<int> Watermark {
      get {
        return this.WorkItem.Field<System.Nullable<int>>("System.Watermark");
      }
    }
  }
  
  [WiLinq.LinqProvider.Extensions.WorkItemTypeAttribute("Feedback Request")]
  public partial class FeedbackRequest : WiLinq.LinqProvider.Extensions.WorkItemBase {
    
    /// <summary>Instructions to launch the specified application</summary>
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.Feedback.ApplicationLaunchInstructions")]
    public virtual string ApplicationLaunchInstructions {
      get {
        return this.WorkItem.Field<string>("Microsoft.VSTS.Feedback.ApplicationLaunchInstructions");
      }
      set {
        this.WorkItem.SetField<string>("Microsoft.VSTS.Feedback.ApplicationLaunchInstructions", value);
      }
    }
    
    /// <summary>The path to execute the application</summary>
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.Feedback.ApplicationStartInformation")]
    public virtual string ApplicationStartInformation {
      get {
        return this.WorkItem.Field<string>("Microsoft.VSTS.Feedback.ApplicationStartInformation");
      }
      set {
        this.WorkItem.SetField<string>("Microsoft.VSTS.Feedback.ApplicationStartInformation", value);
      }
    }
    
    /// <summary>The type of application on which to give feedback</summary>
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.Feedback.ApplicationType")]
    public virtual string ApplicationType {
      get {
        return this.WorkItem.Field<string>("Microsoft.VSTS.Feedback.ApplicationType");
      }
      set {
        this.WorkItem.SetField<string>("Microsoft.VSTS.Feedback.ApplicationType", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("System.AuthorizedAs")]
    public virtual string AuthorizedAs {
      get {
        return this.WorkItem.Field<string>("System.AuthorizedAs");
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("System.AuthorizedDate")]
    public virtual System.Nullable<System.DateTime> AuthorizedDate {
      get {
        return this.WorkItem.Field<System.Nullable<System.DateTime>>("System.AuthorizedDate");
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.Common.ClosedBy")]
    public virtual string ClosedBy {
      get {
        return this.WorkItem.Field<string>("Microsoft.VSTS.Common.ClosedBy");
      }
      set {
        this.WorkItem.SetField<string>("Microsoft.VSTS.Common.ClosedBy", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.Common.ClosedDate")]
    public virtual System.Nullable<System.DateTime> ClosedDate {
      get {
        return this.WorkItem.Field<System.Nullable<System.DateTime>>("Microsoft.VSTS.Common.ClosedDate");
      }
      set {
        this.WorkItem.SetField<System.Nullable<System.DateTime>>("Microsoft.VSTS.Common.ClosedDate", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.Build.IntegrationBuild")]
    public virtual string IntegrationBuild {
      get {
        return this.WorkItem.Field<string>("Microsoft.VSTS.Build.IntegrationBuild");
      }
      set {
        this.WorkItem.SetField<string>("Microsoft.VSTS.Build.IntegrationBuild", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("System.RevisedDate")]
    public virtual System.Nullable<System.DateTime> RevisedDate {
      get {
        return this.WorkItem.Field<System.Nullable<System.DateTime>>("System.RevisedDate");
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("System.Tags")]
    public virtual string Tags {
      get {
        return this.WorkItem.Field<string>("System.Tags");
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("System.Watermark")]
    public virtual System.Nullable<int> Watermark {
      get {
        return this.WorkItem.Field<System.Nullable<int>>("System.Watermark");
      }
    }
  }
  
  [WiLinq.LinqProvider.Extensions.WorkItemTypeAttribute("Feedback Response")]
  public partial class FeedbackResponse : WiLinq.LinqProvider.Extensions.WorkItemBase {
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("System.AuthorizedAs")]
    public virtual string AuthorizedAs {
      get {
        return this.WorkItem.Field<string>("System.AuthorizedAs");
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("System.AuthorizedDate")]
    public virtual System.Nullable<System.DateTime> AuthorizedDate {
      get {
        return this.WorkItem.Field<System.Nullable<System.DateTime>>("System.AuthorizedDate");
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.Common.ClosedBy")]
    public virtual string ClosedBy {
      get {
        return this.WorkItem.Field<string>("Microsoft.VSTS.Common.ClosedBy");
      }
      set {
        this.WorkItem.SetField<string>("Microsoft.VSTS.Common.ClosedBy", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.Common.ClosedDate")]
    public virtual System.Nullable<System.DateTime> ClosedDate {
      get {
        return this.WorkItem.Field<System.Nullable<System.DateTime>>("Microsoft.VSTS.Common.ClosedDate");
      }
      set {
        this.WorkItem.SetField<System.Nullable<System.DateTime>>("Microsoft.VSTS.Common.ClosedDate", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.Build.IntegrationBuild")]
    public virtual string IntegrationBuild {
      get {
        return this.WorkItem.Field<string>("Microsoft.VSTS.Build.IntegrationBuild");
      }
      set {
        this.WorkItem.SetField<string>("Microsoft.VSTS.Build.IntegrationBuild", value);
      }
    }
    
    /// <summary>Overall rating provided as part of feedback response</summary>
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.Common.Rating")]
    public virtual string Rating {
      get {
        return this.WorkItem.Field<string>("Microsoft.VSTS.Common.Rating");
      }
      set {
        this.WorkItem.SetField<string>("Microsoft.VSTS.Common.Rating", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("System.RevisedDate")]
    public virtual System.Nullable<System.DateTime> RevisedDate {
      get {
        return this.WorkItem.Field<System.Nullable<System.DateTime>>("System.RevisedDate");
      }
    }
    
    /// <summary>Test context, provided automatically by test infrastructure</summary>
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.TCM.SystemInfo")]
    public virtual string SystemInfo {
      get {
        return this.WorkItem.Field<string>("Microsoft.VSTS.TCM.SystemInfo");
      }
      set {
        this.WorkItem.SetField<string>("Microsoft.VSTS.TCM.SystemInfo", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("System.Tags")]
    public virtual string Tags {
      get {
        return this.WorkItem.Field<string>("System.Tags");
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("System.Watermark")]
    public virtual System.Nullable<int> Watermark {
      get {
        return this.WorkItem.Field<System.Nullable<int>>("System.Watermark");
      }
    }
  }
  
  [WiLinq.LinqProvider.Extensions.WorkItemTypeAttribute("Impediment")]
  public partial class Impediment : WiLinq.LinqProvider.Extensions.WorkItemBase {
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("System.AuthorizedAs")]
    public virtual string AuthorizedAs {
      get {
        return this.WorkItem.Field<string>("System.AuthorizedAs");
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("System.AuthorizedDate")]
    public virtual System.Nullable<System.DateTime> AuthorizedDate {
      get {
        return this.WorkItem.Field<System.Nullable<System.DateTime>>("System.AuthorizedDate");
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.Build.IntegrationBuild")]
    public virtual string IntegrationBuild {
      get {
        return this.WorkItem.Field<string>("Microsoft.VSTS.Build.IntegrationBuild");
      }
      set {
        this.WorkItem.SetField<string>("Microsoft.VSTS.Build.IntegrationBuild", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.Common.Priority")]
    public virtual System.Nullable<int> Priority {
      get {
        return this.WorkItem.Field<System.Nullable<int>>("Microsoft.VSTS.Common.Priority");
      }
      set {
        this.WorkItem.SetField<System.Nullable<int>>("Microsoft.VSTS.Common.Priority", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.Common.Resolution")]
    public virtual string Resolution {
      get {
        return this.WorkItem.Field<string>("Microsoft.VSTS.Common.Resolution");
      }
      set {
        this.WorkItem.SetField<string>("Microsoft.VSTS.Common.Resolution", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("System.RevisedDate")]
    public virtual System.Nullable<System.DateTime> RevisedDate {
      get {
        return this.WorkItem.Field<System.Nullable<System.DateTime>>("System.RevisedDate");
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("System.Tags")]
    public virtual string Tags {
      get {
        return this.WorkItem.Field<string>("System.Tags");
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("System.Watermark")]
    public virtual System.Nullable<int> Watermark {
      get {
        return this.WorkItem.Field<System.Nullable<int>>("System.Watermark");
      }
    }
  }
  
  [WiLinq.LinqProvider.Extensions.WorkItemTypeAttribute("Product Backlog Item")]
  public partial class ProductBacklogItem : WiLinq.LinqProvider.Extensions.WorkItemBase {
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.Common.AcceptanceCriteria")]
    public virtual string AcceptanceCriteria {
      get {
        return this.WorkItem.Field<string>("Microsoft.VSTS.Common.AcceptanceCriteria");
      }
      set {
        this.WorkItem.SetField<string>("Microsoft.VSTS.Common.AcceptanceCriteria", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("System.AuthorizedAs")]
    public virtual string AuthorizedAs {
      get {
        return this.WorkItem.Field<string>("System.AuthorizedAs");
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("System.AuthorizedDate")]
    public virtual System.Nullable<System.DateTime> AuthorizedDate {
      get {
        return this.WorkItem.Field<System.Nullable<System.DateTime>>("System.AuthorizedDate");
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.Common.BacklogPriority")]
    public virtual System.Nullable<double> BacklogPriority {
      get {
        return this.WorkItem.Field<System.Nullable<double>>("Microsoft.VSTS.Common.BacklogPriority");
      }
      set {
        this.WorkItem.SetField<System.Nullable<double>>("Microsoft.VSTS.Common.BacklogPriority", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.Common.BusinessValue")]
    public virtual System.Nullable<int> BusinessValue {
      get {
        return this.WorkItem.Field<System.Nullable<int>>("Microsoft.VSTS.Common.BusinessValue");
      }
      set {
        this.WorkItem.SetField<System.Nullable<int>>("Microsoft.VSTS.Common.BusinessValue", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.Common.ClosedDate")]
    public virtual System.Nullable<System.DateTime> ClosedDate {
      get {
        return this.WorkItem.Field<System.Nullable<System.DateTime>>("Microsoft.VSTS.Common.ClosedDate");
      }
      set {
        this.WorkItem.SetField<System.Nullable<System.DateTime>>("Microsoft.VSTS.Common.ClosedDate", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.Scheduling.Effort")]
    public virtual System.Nullable<double> Effort {
      get {
        return this.WorkItem.Field<System.Nullable<double>>("Microsoft.VSTS.Scheduling.Effort");
      }
      set {
        this.WorkItem.SetField<System.Nullable<double>>("Microsoft.VSTS.Scheduling.Effort", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.Build.IntegrationBuild")]
    public virtual string IntegrationBuild {
      get {
        return this.WorkItem.Field<string>("Microsoft.VSTS.Build.IntegrationBuild");
      }
      set {
        this.WorkItem.SetField<string>("Microsoft.VSTS.Build.IntegrationBuild", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("System.RevisedDate")]
    public virtual System.Nullable<System.DateTime> RevisedDate {
      get {
        return this.WorkItem.Field<System.Nullable<System.DateTime>>("System.RevisedDate");
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("System.Tags")]
    public virtual string Tags {
      get {
        return this.WorkItem.Field<string>("System.Tags");
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("System.Watermark")]
    public virtual System.Nullable<int> Watermark {
      get {
        return this.WorkItem.Field<System.Nullable<int>>("System.Watermark");
      }
    }
  }
  
  [WiLinq.LinqProvider.Extensions.WorkItemTypeAttribute("Shared Steps")]
  public partial class SharedSteps : WiLinq.LinqProvider.Extensions.WorkItemBase {
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.Common.ActivatedBy")]
    public virtual string ActivatedBy {
      get {
        return this.WorkItem.Field<string>("Microsoft.VSTS.Common.ActivatedBy");
      }
      set {
        this.WorkItem.SetField<string>("Microsoft.VSTS.Common.ActivatedBy", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.Common.ActivatedDate")]
    public virtual System.Nullable<System.DateTime> ActivatedDate {
      get {
        return this.WorkItem.Field<System.Nullable<System.DateTime>>("Microsoft.VSTS.Common.ActivatedDate");
      }
      set {
        this.WorkItem.SetField<System.Nullable<System.DateTime>>("Microsoft.VSTS.Common.ActivatedDate", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("System.AuthorizedAs")]
    public virtual string AuthorizedAs {
      get {
        return this.WorkItem.Field<string>("System.AuthorizedAs");
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("System.AuthorizedDate")]
    public virtual System.Nullable<System.DateTime> AuthorizedDate {
      get {
        return this.WorkItem.Field<System.Nullable<System.DateTime>>("System.AuthorizedDate");
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.Common.ClosedBy")]
    public virtual string ClosedBy {
      get {
        return this.WorkItem.Field<string>("Microsoft.VSTS.Common.ClosedBy");
      }
      set {
        this.WorkItem.SetField<string>("Microsoft.VSTS.Common.ClosedBy", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.Common.ClosedDate")]
    public virtual System.Nullable<System.DateTime> ClosedDate {
      get {
        return this.WorkItem.Field<System.Nullable<System.DateTime>>("Microsoft.VSTS.Common.ClosedDate");
      }
      set {
        this.WorkItem.SetField<System.Nullable<System.DateTime>>("Microsoft.VSTS.Common.ClosedDate", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.Build.IntegrationBuild")]
    public virtual string IntegrationBuild {
      get {
        return this.WorkItem.Field<string>("Microsoft.VSTS.Build.IntegrationBuild");
      }
      set {
        this.WorkItem.SetField<string>("Microsoft.VSTS.Build.IntegrationBuild", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.Common.Issue")]
    public virtual string Issue {
      get {
        return this.WorkItem.Field<string>("Microsoft.VSTS.Common.Issue");
      }
      set {
        this.WorkItem.SetField<string>("Microsoft.VSTS.Common.Issue", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.TCM.Parameters")]
    public virtual string Parameters {
      get {
        return this.WorkItem.Field<string>("Microsoft.VSTS.TCM.Parameters");
      }
      set {
        this.WorkItem.SetField<string>("Microsoft.VSTS.TCM.Parameters", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.Common.Priority")]
    public virtual System.Nullable<int> Priority {
      get {
        return this.WorkItem.Field<System.Nullable<int>>("Microsoft.VSTS.Common.Priority");
      }
      set {
        this.WorkItem.SetField<System.Nullable<int>>("Microsoft.VSTS.Common.Priority", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("System.RevisedDate")]
    public virtual System.Nullable<System.DateTime> RevisedDate {
      get {
        return this.WorkItem.Field<System.Nullable<System.DateTime>>("System.RevisedDate");
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.Common.StateChangeDate")]
    public virtual System.Nullable<System.DateTime> StateChangeDate {
      get {
        return this.WorkItem.Field<System.Nullable<System.DateTime>>("Microsoft.VSTS.Common.StateChangeDate");
      }
      set {
        this.WorkItem.SetField<System.Nullable<System.DateTime>>("Microsoft.VSTS.Common.StateChangeDate", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.TCM.Steps")]
    public virtual string Steps {
      get {
        return this.WorkItem.Field<string>("Microsoft.VSTS.TCM.Steps");
      }
      set {
        this.WorkItem.SetField<string>("Microsoft.VSTS.TCM.Steps", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("System.Tags")]
    public virtual string Tags {
      get {
        return this.WorkItem.Field<string>("System.Tags");
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("System.Watermark")]
    public virtual System.Nullable<int> Watermark {
      get {
        return this.WorkItem.Field<System.Nullable<int>>("System.Watermark");
      }
    }
  }
  
  [WiLinq.LinqProvider.Extensions.WorkItemTypeAttribute("Test Case")]
  public partial class TestCase : WiLinq.LinqProvider.Extensions.WorkItemBase {
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.Common.ActivatedBy")]
    public virtual string ActivatedBy {
      get {
        return this.WorkItem.Field<string>("Microsoft.VSTS.Common.ActivatedBy");
      }
      set {
        this.WorkItem.SetField<string>("Microsoft.VSTS.Common.ActivatedBy", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.Common.ActivatedDate")]
    public virtual System.Nullable<System.DateTime> ActivatedDate {
      get {
        return this.WorkItem.Field<System.Nullable<System.DateTime>>("Microsoft.VSTS.Common.ActivatedDate");
      }
      set {
        this.WorkItem.SetField<System.Nullable<System.DateTime>>("Microsoft.VSTS.Common.ActivatedDate", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("System.AuthorizedAs")]
    public virtual string AuthorizedAs {
      get {
        return this.WorkItem.Field<string>("System.AuthorizedAs");
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("System.AuthorizedDate")]
    public virtual System.Nullable<System.DateTime> AuthorizedDate {
      get {
        return this.WorkItem.Field<System.Nullable<System.DateTime>>("System.AuthorizedDate");
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.TCM.AutomatedTestId")]
    public virtual string AutomatedTestId {
      get {
        return this.WorkItem.Field<string>("Microsoft.VSTS.TCM.AutomatedTestId");
      }
      set {
        this.WorkItem.SetField<string>("Microsoft.VSTS.TCM.AutomatedTestId", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.TCM.AutomatedTestName")]
    public virtual string AutomatedTestName {
      get {
        return this.WorkItem.Field<string>("Microsoft.VSTS.TCM.AutomatedTestName");
      }
      set {
        this.WorkItem.SetField<string>("Microsoft.VSTS.TCM.AutomatedTestName", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.TCM.AutomatedTestStorage")]
    public virtual string AutomatedTestStorage {
      get {
        return this.WorkItem.Field<string>("Microsoft.VSTS.TCM.AutomatedTestStorage");
      }
      set {
        this.WorkItem.SetField<string>("Microsoft.VSTS.TCM.AutomatedTestStorage", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.TCM.AutomatedTestType")]
    public virtual string AutomatedTestType {
      get {
        return this.WorkItem.Field<string>("Microsoft.VSTS.TCM.AutomatedTestType");
      }
      set {
        this.WorkItem.SetField<string>("Microsoft.VSTS.TCM.AutomatedTestType", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.TCM.AutomationStatus")]
    public virtual string Automationstatus {
      get {
        return this.WorkItem.Field<string>("Microsoft.VSTS.TCM.AutomationStatus");
      }
      set {
        this.WorkItem.SetField<string>("Microsoft.VSTS.TCM.AutomationStatus", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.Common.ClosedBy")]
    public virtual string ClosedBy {
      get {
        return this.WorkItem.Field<string>("Microsoft.VSTS.Common.ClosedBy");
      }
      set {
        this.WorkItem.SetField<string>("Microsoft.VSTS.Common.ClosedBy", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.Common.ClosedDate")]
    public virtual System.Nullable<System.DateTime> ClosedDate {
      get {
        return this.WorkItem.Field<System.Nullable<System.DateTime>>("Microsoft.VSTS.Common.ClosedDate");
      }
      set {
        this.WorkItem.SetField<System.Nullable<System.DateTime>>("Microsoft.VSTS.Common.ClosedDate", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.Build.IntegrationBuild")]
    public virtual string IntegrationBuild {
      get {
        return this.WorkItem.Field<string>("Microsoft.VSTS.Build.IntegrationBuild");
      }
      set {
        this.WorkItem.SetField<string>("Microsoft.VSTS.Build.IntegrationBuild", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.TCM.LocalDataSource")]
    public virtual string LocalDataSource {
      get {
        return this.WorkItem.Field<string>("Microsoft.VSTS.TCM.LocalDataSource");
      }
      set {
        this.WorkItem.SetField<string>("Microsoft.VSTS.TCM.LocalDataSource", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.TCM.Parameters")]
    public virtual string Parameters {
      get {
        return this.WorkItem.Field<string>("Microsoft.VSTS.TCM.Parameters");
      }
      set {
        this.WorkItem.SetField<string>("Microsoft.VSTS.TCM.Parameters", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.Common.Priority")]
    public virtual System.Nullable<int> Priority {
      get {
        return this.WorkItem.Field<System.Nullable<int>>("Microsoft.VSTS.Common.Priority");
      }
      set {
        this.WorkItem.SetField<System.Nullable<int>>("Microsoft.VSTS.Common.Priority", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("System.RevisedDate")]
    public virtual System.Nullable<System.DateTime> RevisedDate {
      get {
        return this.WorkItem.Field<System.Nullable<System.DateTime>>("System.RevisedDate");
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.Common.StateChangeDate")]
    public virtual System.Nullable<System.DateTime> StateChangeDate {
      get {
        return this.WorkItem.Field<System.Nullable<System.DateTime>>("Microsoft.VSTS.Common.StateChangeDate");
      }
      set {
        this.WorkItem.SetField<System.Nullable<System.DateTime>>("Microsoft.VSTS.Common.StateChangeDate", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("Microsoft.VSTS.TCM.Steps")]
    public virtual string Steps {
      get {
        return this.WorkItem.Field<string>("Microsoft.VSTS.TCM.Steps");
      }
      set {
        this.WorkItem.SetField<string>("Microsoft.VSTS.TCM.Steps", value);
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("System.Tags")]
    public virtual string Tags {
      get {
        return this.WorkItem.Field<string>("System.Tags");
      }
    }
    
    [WiLinq.LinqProvider.Extensions.FieldAttribute("System.Watermark")]
    public virtual System.Nullable<int> Watermark {
      get {
        return this.WorkItem.Field<System.Nullable<int>>("System.Watermark");
      }
    }
  }
}
